CREATE TABLE IF NOT EXISTS nodes (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  node_id VARCHAR(64) NOT NULL COMMENT '代理节点唯一标识',
  name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '节点名称',
  region VARCHAR(64) NOT NULL DEFAULT '' COMMENT '节点所在地域或可用区',
  provider VARCHAR(64) NOT NULL DEFAULT '' COMMENT '云厂商或VPS服务商',
  network_line VARCHAR(128) NOT NULL DEFAULT '' COMMENT '节点网络线路，例如CN2 GIA/9929/CMI/BGP',
  tag VARCHAR(128) NOT NULL DEFAULT '' COMMENT '节点标签',
  public_ip VARCHAR(64) NOT NULL DEFAULT '' COMMENT '默认公网IPv4地址',
  public_ipv6 VARCHAR(128) NOT NULL DEFAULT '' COMMENT '默认公网IPv6地址',
  public_ips_json JSON NULL COMMENT '观测到的公网IPv4/IPv6历史列表，格式：{"ipv4":[],"ipv6":[]}',
  ip_addresses_json JSON NULL COMMENT 'Agent 枚举到的 IPv4/IPv6 地址列表，格式：{"ipv4":[],"ipv6":[]}',
  status VARCHAR(32) NOT NULL DEFAULT 'offline' COMMENT '节点状态：online在线，offline离线，unknown未知',
  agent_version VARCHAR(64) NOT NULL DEFAULT '' COMMENT '代理程序版本号',
  secret_key_hash VARCHAR(255) NOT NULL DEFAULT '' COMMENT '连接密钥哈希值',
  secret_key_encrypted TEXT NULL COMMENT '加密后的连接密钥内容',
  last_seen_at BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '最后一次心跳时间戳，Unix毫秒',
  heartbeat_interval INT UNSIGNED NOT NULL DEFAULT 15 COMMENT '心跳间隔，单位秒，由master下发',
  metrics_interval INT UNSIGNED NOT NULL DEFAULT 15 COMMENT '指标上报间隔，单位秒，由master下发',
  snapshot_override TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否覆盖全局快照采集配置',
  snapshot_enabled TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否启用进程与连接快照采集',
  snapshot_collect_processes TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否采集进程快照',
  snapshot_collect_connections TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否采集连接快照',
  snapshot_mask_sensitive TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否脱敏快照敏感数据',
  snapshot_interval INT UNSIGNED NOT NULL DEFAULT 60 COMMENT '快照采集间隔，单位秒，由master下发',
  snapshot_process_limit INT UNSIGNED NOT NULL DEFAULT 20 COMMENT '每次上报的进程快照最大条数',
  snapshot_connection_limit INT UNSIGNED NOT NULL DEFAULT 200 COMMENT '每次上报的连接快照最大条数',
  billing_cycle VARCHAR(32) NOT NULL DEFAULT 'monthly' COMMENT '付费周期：daily/monthly/yearly/one_time',
  price_amount DOUBLE NOT NULL DEFAULT 0 COMMENT '付费金额',
  currency VARCHAR(16) NOT NULL DEFAULT 'CNY' COMMENT '币种，例如CNY/USD/EUR',
  service_started_at BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '服务开始时间戳，Unix毫秒',
  service_expires_at BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '服务到期时间戳，Unix毫秒',
  traffic_limit_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '套餐总流量，单位字节，0表示不限',
  traffic_calibration_bytes BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '当前重置周期流量校准值，单位字节',
  traffic_calibration_at BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '校准流量设置时间戳，Unix毫秒',
  traffic_billing_direction VARCHAR(32) NOT NULL DEFAULT 'bidirectional' COMMENT '流量计费方向：bidirectional/outbound',
  traffic_reset_cycle VARCHAR(32) NOT NULL DEFAULT 'monthly' COMMENT '流量重置周期：daily/monthly/yearly/never',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_nodes_node_id (node_id),
  KEY idx_nodes_status (status),
  KEY idx_nodes_last_seen_at (last_seen_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='代理节点表';

CREATE TABLE IF NOT EXISTS node_metrics (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  node_id VARCHAR(64) NOT NULL COMMENT '代理节点唯一标识',
  ts BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '指标采样时间戳，Unix毫秒',
  cpu_usage DOUBLE NOT NULL DEFAULT 0 COMMENT '处理器使用率百分比',
  cpu_cores INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '处理器核心数量',
  arch VARCHAR(32) NOT NULL DEFAULT '' COMMENT '处理器架构，例如amd、arm',
  virtualization VARCHAR(64) NOT NULL DEFAULT '' COMMENT '虚拟化类型，例如kvm、qemu、vmware',
  gpu VARCHAR(255) NOT NULL DEFAULT '' COMMENT '显卡信息',
  os_name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '操作系统详细名称',
  load1 DOUBLE NOT NULL DEFAULT 0 COMMENT '1分钟平均负载',
  load5 DOUBLE NOT NULL DEFAULT 0 COMMENT '5分钟平均负载',
  load15 DOUBLE NOT NULL DEFAULT 0 COMMENT '15分钟平均负载',
  mem_total BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '内存总量，单位字节',
  mem_used BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已用内存，单位字节',
  mem_used_percent DOUBLE NOT NULL DEFAULT 0 COMMENT '内存使用率百分比',
  swap_total BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT 'Swap总量，单位字节',
  swap_used BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已用Swap，单位字节',
  swap_used_percent DOUBLE NOT NULL DEFAULT 0 COMMENT 'Swap使用率百分比',
  disk_total BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '磁盘总量，单位字节',
  disk_used BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '已用磁盘，单位字节',
  disk_used_percent DOUBLE NOT NULL DEFAULT 0 COMMENT '磁盘使用率百分比',
  net_rx_bps BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '网络接收速率，单位bit每秒',
  net_tx_bps BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '网络发送速率，单位bit每秒',
  net_rx_bytes_total BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '网络累计接收流量，单位字节',
  net_tx_bytes_total BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '网络累计发送流量，单位字节',
  uptime_seconds BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '系统启动时长，单位秒',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_node_metric_node_ts (node_id, ts),
  KEY idx_node_metrics_ts (ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='节点指标时序数据表';

CREATE TABLE IF NOT EXISTS node_snapshots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  node_id VARCHAR(64) NOT NULL COMMENT '代理节点唯一标识',
  ts BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '快照采样时间戳，Unix毫秒',
  process_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '进程总数',
  thread_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '线程总数',
  connection_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '连接总数',
  listen_count INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '监听连接数量',
  tcp_state_json JSON NULL COMMENT 'TCP状态统计JSON',
  top_process_json JSON NULL COMMENT '进程快照JSON',
  connections_json JSON NULL COMMENT '连接快照JSON',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_node_snapshot_node_ts (node_id, ts),
  KEY idx_node_snapshots_ts (ts)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='节点进程与连接快照表';

CREATE TABLE IF NOT EXISTS probe_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  name VARCHAR(128) NOT NULL DEFAULT '' COMMENT '探测任务名称',
  type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '探测协议，例如tcp_ping、icmp',
  ip_version VARCHAR(16) NOT NULL DEFAULT 'auto' COMMENT 'IP版本：auto、ipv4、ipv6',
  target VARCHAR(255) NOT NULL COMMENT '探测目标地址或URL',
  interval_seconds INT UNSIGNED NOT NULL DEFAULT 60 COMMENT '探测间隔，单位秒',
  timeout_ms INT UNSIGNED NOT NULL DEFAULT 3000 COMMENT '探测超时时间，单位毫秒',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用任务：1启用，0禁用',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  KEY idx_probe_tasks_enabled (enabled),
  KEY idx_probe_tasks_type (type),
  KEY idx_probe_tasks_ip_version (ip_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='探测任务定义表';

CREATE TABLE IF NOT EXISTS probe_task_assignments (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  node_id VARCHAR(64) NOT NULL COMMENT '代理节点唯一标识',
  task_id BIGINT UNSIGNED NOT NULL COMMENT '探测任务ID',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_probe_task_assignment_node_task (node_id, task_id),
  KEY idx_probe_task_assignments_node_id (node_id),
  KEY idx_probe_task_assignments_task_id (task_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='节点探测任务关联表';

CREATE TABLE IF NOT EXISTS probe_results (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  task_id BIGINT UNSIGNED NOT NULL COMMENT '探测任务ID',
  node_id VARCHAR(64) NOT NULL COMMENT '代理节点唯一标识',
  type VARCHAR(32) NOT NULL DEFAULT '' COMMENT '探测协议，例如tcp_ping、icmp',
  ip_version VARCHAR(16) NOT NULL DEFAULT 'auto' COMMENT 'IP版本：auto、ipv4、ipv6',
  target VARCHAR(255) NOT NULL COMMENT '探测目标地址或URL',
  status VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT '探测结果状态：success成功，failed失败，unknown未知',
  latency_ms DOUBLE NULL DEFAULT NULL COMMENT '探测延迟，单位毫秒',
  packet_loss DOUBLE NULL DEFAULT NULL COMMENT '丢包率百分比',
  http_status INT NULL DEFAULT NULL COMMENT '网页响应状态码',
  error_message TEXT NULL COMMENT '失败原因或错误详情',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_probe_result_task_created (task_id, created_at),
  KEY idx_probe_result_node_created (node_id, created_at),
  KEY idx_probe_results_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='探测执行结果表';

CREATE TABLE IF NOT EXISTS alerts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  node_id VARCHAR(64) NOT NULL COMMENT '代理节点唯一标识',
  rule_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '告警规则类型',
  level VARCHAR(32) NOT NULL DEFAULT 'warning' COMMENT '告警级别：info信息，warning警告，critical严重',
  status VARCHAR(32) NOT NULL DEFAULT 'active' COMMENT '告警状态：active触发中，resolved已恢复',
  message TEXT NULL COMMENT '告警消息内容',
  first_triggered_at BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '首次触发时间戳，Unix毫秒',
  last_triggered_at BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '最近触发时间戳，Unix毫秒',
  resolved_at BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '恢复时间戳，Unix毫秒',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  KEY idx_alert_node_status (node_id, status),
  KEY idx_alert_level_status (level, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='节点告警表';

CREATE TABLE IF NOT EXISTS node_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  node_id VARCHAR(64) NOT NULL COMMENT '代理节点唯一标识',
  event_type VARCHAR(64) NOT NULL DEFAULT '' COMMENT '节点事件类型',
  message TEXT NULL COMMENT '事件消息内容',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_node_event_node_created (node_id, created_at),
  KEY idx_node_event_type_created (event_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='节点事件时间线表';

CREATE TABLE IF NOT EXISTS system_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  service VARCHAR(32) NOT NULL DEFAULT '' COMMENT '日志来源服务：master/agent',
  node_id VARCHAR(64) NOT NULL DEFAULT '' COMMENT '关联节点ID',
  level VARCHAR(16) NOT NULL DEFAULT 'info' COMMENT '日志级别',
  event_type VARCHAR(64) NOT NULL DEFAULT 'system.event' COMMENT '事件类型',
  message TEXT NULL COMMENT '日志消息',
  meta_json JSON NULL COMMENT '结构化上下文',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id),
  KEY idx_system_log_service_created (service, created_at),
  KEY idx_system_log_node_created (node_id, created_at),
  KEY idx_system_log_level_created (level, created_at),
  KEY idx_system_log_event_created (event_type, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='系统日志表';

CREATE TABLE IF NOT EXISTS app_settings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `key` VARCHAR(96) NOT NULL COMMENT '设置键',
  value MEDIUMTEXT NOT NULL COMMENT '设置值',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_app_settings_key (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='全局设置表';

INSERT INTO app_settings (`key`, value)
VALUES
  ('show_home_summary', 'true'),
  ('show_billing_details', 'true'),
  ('show_traffic_plan', 'true'),
  ('show_node_tags', 'true'),
  ('mask_ip_addresses', 'false'),
  ('site_name', 'Rivo Monitor'),
  ('site_avatar_base64', ''),
  ('active_theme', 'default'),
  ('admin_path', ''),
  ('snapshot_enabled', 'false'),
  ('snapshot_collect_processes', 'true'),
  ('snapshot_collect_connections', 'true'),
  ('snapshot_mask_sensitive', 'true'),
  ('snapshot_interval_seconds', '60'),
  ('snapshot_process_limit', '20'),
  ('snapshot_connection_limit', '200'),
  ('metrics_retention_months', '6'),
  ('asset_base_currency', 'CNY'),
  ('exchange_rate_auto_update', 'true'),
  ('wecom_webhook_enabled', 'false'),
  ('wecom_webhook_url', ''),
  ('telegram_enabled', 'false'),
  ('telegram_bot_token', ''),
  ('telegram_chat_id', ''),
  ('email_enabled', 'false'),
  ('email_smtp_host', ''),
  ('email_smtp_port', '587'),
  ('email_smtp_security', 'starttls'),
  ('email_smtp_username', ''),
  ('email_smtp_password', ''),
  ('email_from', ''),
  ('email_to', ''),
  ('traffic_alert_enabled', 'true'),
  ('traffic_alert_percent', '80'),
  ('cpu_alert_enabled', 'true'),
  ('cpu_alert_percent', '85'),
  ('memory_alert_enabled', 'true'),
  ('memory_alert_percent', '85'),
  ('disk_load_alert_enabled', 'true'),
  ('disk_load_alert_percent', '90'),
  ('load_alert_enabled', 'true'),
  ('load_alert_threshold', '5'),
  ('alert_interval_minutes', '30'),
  ('offline_alert_delay_minutes', '1'),
  ('expiry_alert_enabled', 'true'),
  ('expiry_alert_days', '7')
ON DUPLICATE KEY UPDATE `key` = VALUES(`key`);

CREATE TABLE IF NOT EXISTS region_options (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  code VARCHAR(16) NOT NULL COMMENT '地区代码，例如default、HK、US、JP',
  name VARCHAR(64) NOT NULL DEFAULT '' COMMENT '地区显示名称',
  sort_order INT NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前',
  enabled TINYINT(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用，0禁用',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (id),
  UNIQUE KEY uk_region_options_code (code),
  KEY idx_region_options_enabled_sort (enabled, sort_order)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='地区代码选项表';

INSERT INTO region_options (code, name, sort_order, enabled)
VALUES
  ('default', '默认', 0, 1),
  ('HK', '香港', 10, 1),
  ('US', '美国', 20, 1),
  ('JP', '日本', 30, 1),
  ('SG', '新加坡', 40, 1),
  ('TW', '台湾', 50, 1),
  ('KR', '韩国', 60, 1),
  ('CN', '中国', 70, 1),
  ('DE', '德国', 80, 1),
  ('FR', '法国', 90, 1),
  ('GB', '英国', 100, 1),
  ('NL', '荷兰', 110, 1),
  ('CA', '加拿大', 120, 1),
  ('AU', '澳大利亚', 130, 1),
  ('AE', '阿联酋', 140, 1),
  ('TH', '泰国', 150, 1),
  ('VN', '越南', 160, 1),
  ('IN', '印度', 170, 1),
  ('ID', '印尼', 180, 1),
  ('MY', '马来西亚', 190, 1),
  ('PH', '菲律宾', 200, 1),
  ('BR', '巴西', 210, 1),
  ('RU', '俄罗斯', 220, 1),
  ('TR', '土耳其', 230, 1)
ON DUPLICATE KEY UPDATE code = VALUES(code);
